@startuml

box "PIONEER" #LightBlue
actor Becca
database PIONEER
collections keystore
database BECCADB
end box

box "Stats" #Orange
actor Alice
database SECRETS
end box

== Encrypt PIONEER data ==

PIONEER -> Becca: PIONEER data
Becca -> keystore: Generate and store key
Becca -> Becca: Encrypt PIONEER data
Becca <- BECCADB: encrypted PIONEER data

== Send encrypted PIONEER data ==
Becca -> Alice: encrypted PIONEER data

== Retrieve secret data ==
SECRETS -> Alice: Secret data

== Combine and return data ==
Alice -> Alice: Combine data
Alice -> Becca: Combined data

== Store and Decrypt data ==
keystore -> Becca: Retrieve key
Becca -> Becca: Decrypt
Becca -> BECCADB: Store combined data

@enduml
