@startuml

actor Becca
actor Alice

database PIONEER
database SECRETS
database BECCADB

collections keystore

PIONEER -> Becca: PIONEER data
Becca -> keystore: Generate and store key
Becca -> BECCADB: encrypted PIONEER data




@enduml
