@startuml

box "PIONEER" #LightBlue
actor Becca
database PIONEER
collections keystore
end box

box "Stats" #Orange
actor Alice
database SECRETS
end box

== Encrypt PIONEER data ==

PIONEER -> Becca: PIONEER data
Becca -> keystore: Generate and store key

== Store and send encrypted PIONEER data ==

create database BECCADB
Becca -> BECCADB: encrypted PIONEER data
Becca -> Alice: encrypted PIONEER data


@enduml
